// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWz4z7wkMnVZlQNOzc2ui4wTUFpL9Muqo',
    appId: '1:702172540474:web:0520b6ccdf06537ebf8f03',
    messagingSenderId: '702172540474',
    projectId: 'todo-app-e8a96',
    authDomain: 'todo-app-e8a96.firebaseapp.com',
    storageBucket: 'todo-app-e8a96.appspot.com',
    measurementId: 'G-7809E4FKZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKxe9rNU2hn7W9jk-sSn8uLAm87bYndj4',
    appId: '1:702172540474:android:860e689fa3bcdb73bf8f03',
    messagingSenderId: '702172540474',
    projectId: 'todo-app-e8a96',
    storageBucket: 'todo-app-e8a96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGiACj4T-3pbPNm3RYM7aluogit4Nd6Rc',
    appId: '1:702172540474:ios:95323d164ec9f2cbbf8f03',
    messagingSenderId: '702172540474',
    projectId: 'todo-app-e8a96',
    storageBucket: 'todo-app-e8a96.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGiACj4T-3pbPNm3RYM7aluogit4Nd6Rc',
    appId: '1:702172540474:ios:8276af034e2641d8bf8f03',
    messagingSenderId: '702172540474',
    projectId: 'todo-app-e8a96',
    storageBucket: 'todo-app-e8a96.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
